<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLJJx5y1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLJJx5y1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLJJx5y1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLJJx5y1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLJJx5y1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LJJx5y1',
    'container.build_id' => 'e89ea1ea',
    'container.build_time' => 1588009758,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLJJx5y1');
